version: "3"

services:
    datanode: 
      image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
      container_name: datanode
      restart: always
      volumes:
        - hadoop_datanode:/hadoop/dfs/data
      environment:
        SERVICE_PRECONDITION: "172.16.2.16:9870"
      env_file:
        - ./hadoop.env

volumes:
  hadoop_datanode: